spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:15432/demo1"
    username: postgres
    password: password
  jpa:
    open-in-view: false
  docker:
    compose:
      # details at https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.docker-compose.lifecycle
      lifecycle-management: start-and-stop
      start:
        command: up
      stop:
        command: down
        timeout: 1m

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


